spring.application.name=trektrace

spring.mongodb.uri=mongodb+srv://userOne:JUECc9PuA8RE5X69@cluster0.bff6seb.mongodb.net/travel
spring.mongodb.database=travel

jwt.secret=23511d7b9372a189193dd52487002f2c
 
