spring.application.name=trektrace

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE:travel}

jwt.secret=${JWT_SECRET}
 
appwrite.projectId=${APPWRITE_PROJECT_ID}
appwrite.apiKey=${APPWRITE_API_KEY}
appwrite.endpoint=${APPWRITE_ENDPOINT:https://cloud.appwrite.io/v1}
